name: messenger
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  provider: ^6.1.2
  cloud_firestore: ^5.5.0
  shared_preferences: ^2.3.3
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  flutter_secure_storage: ^9.2.2
  url_launcher: ^6.3.1
  file_picker: ^5.0.2
  insta_image_viewer: ^1.0.4
  firebase_database: ^11.1.6
  intl: ^0.19.0
  flutter_riverpod: ^2.6.1
  firebase_storage: ^12.3.6
  image_picker: ^1.1.2
  uuid: ^4.5.1
  cached_network_image: ^3.4.1
  scrollable_positioned_list: ^0.3.8
  remixicon: ^1.3.0





dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  icons_launcher: ^1.1.9
  
flutter_icons:
  android: "launcher_icon"
  image_path_web: 'assets/chat.png'
  ios: true
  web: true
  image_path: "assets/chat.png"
  min_sdk_android: 21
  remove_alpha_ios: true



# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_intl:
  enabled: true
